name: damoa-assets-automation
on:
  push:
    branches:
    - master
    paths:
      - package.json

jobs:
  damoa-assets-automation:
    name: damoa assets automation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: npm install
    - run: npm run update-version
    - run: npm run fetch
      env:
        FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}
        FIGMA_FILE_URL: ${{ secrets.FIGMA_FILE_URL }}
    - run: npm run generate
    - run: npm build
    - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc
    - run: npm run publish:libraries
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    - name: GIT commit and push all changed files
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        branch: 'master'
